# Configuración principal
exchange: binance
symbols: ["BTC/USDT"]
timeframe: "1m"   # "1s" si disponible; si no, se simula desde 1m
fees:
  taker: 0.001
  maker: 0.001
slippage: 0.0005          # 5 bps
min_notional_usd: 10.0
filters:
  tickSize: 0.01
  stepSize: 0.0001
step_seconds: 60
rate_limits:
  per_minute: 1200

# Hyperparámetros DRL
algo: "ppo"               # "ppo" | "dqn"
ppo:
  learning_rate: 3.0e-4
  n_steps: 2048
  batch_size: 64
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  entropy_start: 0.01
  entropy_end: 0.0
dqn:
  learning_rate: 1.0e-3
  gamma: 0.99
  batch_size: 64
  buffer_size: 10000
  target_update: 1000
  epsilon_start: 1.0
  epsilon_end: 0.05
  epsilon_decay_steps: 10000

# Reward heads
reward_weights:
  pnl: 1.0
  turn: 0.1
  dd: 0.2
  vol: 0.1

# Deterministic policy params
deterministic_policy:
  base_threshold: 0.001   # required 5-tick log-return to enter
  bounce_coef: 0.5        # sensitivity of threshold to prior drawdown
  trailing_pct: 0.01      # exit when price falls this fraction from peak
  cooldown_ticks: 5       # min ticks between consecutive trades

# Stochastic policy params
stochastic_policy:
  base_threshold: 0.001   # same semantics as deterministic
  bounce_coef: 0.5
  trailing_pct: 0.01
  temperature: 0.1        # softmax temperature tau
  noise_std: 0.0001       # std-dev of Gaussian noise on thresholds
  seed: 42

# Paths
paths:
  data_root: "data"
  raw_dir: "data/raw"
  logs_dir: "logs"
  reports_dir: "reports"
  checkpoints_dir: "checkpoints"
  models_dir: "models"
