# Configuración principal
exchange: binance
symbols: ["BTC/USDT"]
timeframe: "1m"   # "1s" si disponible; si no, se simula desde 1m
fees:
  taker: 0.001
  maker: 0.001
slippage: 0.0005          # 5 bps
min_notional_usd: 10.0
filters:
  tickSize: 0.01
  stepSize: 0.0001
step_seconds: 60
rate_limits:
  per_minute: 1200

# Hyperparámetros DRL
algo: "ppo"               # "ppo" | "dqn"
ppo:
  learning_rate: 3.0e-4
  n_steps: 2048
  batch_size: 64
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.01
dqn:
  learning_rate: 1.0e-3
  gamma: 0.99
  batch_size: 64
  target_update: 1000
  epsilon_start: 1.0
  epsilon_end: 0.05
  epsilon_decay_steps: 10000

# Reward heads
reward_weights:
  pnl: 1.0
  turnover_penalty: 0.1
  drawdown_penalty: 0.2
  volatility_penalty: 0.1

# Paths
paths:
  data_root: "data"
  raw_dir: "data/raw"
  logs_dir: "logs"
  reports_dir: "reports"
  checkpoints_dir: "checkpoints"
