exchange: binance
binance_use_testnet: false
symbols:
- BTC/USDT
- ETH/USDT
- SOL/USDT
- DOGE/USDT
- XRP/USDT
- FDUSD/USDT
- LINK/USDT
- BNB/USDT
- ADA/USDT
- TRX/USDT
- SUI/USDT
- ENA/USDT
- BIO/USDT
- AEUR/USDT
- PEPE/USDT
- PENGU/USDT
- ARB/USDT
- MEME/USDT
- UNI/USDT
- CFX/USDT
timeframe: 1m
fees:
  taker: 0.001
  maker: 0.001
slippage_multiplier: 1.0
min_notional_usd: 10.0
filters:
  tickSize: 0.01
  stepSize: 0.0001
algo: ppo
ppo:
  learning_rate: 0.000776174158803585
  batch_size: 64
  n_steps: 512
dqn:
  learning_rate: 0.001
  gamma: 0.99
  batch_size: 64
  buffer_size: 10000
  target_update: 1000
  epsilon_start: 1.0
  epsilon_end: 0.05
  epsilon_decay_steps: 10000
llm:
  enabled: true
  model: gpt-4o
  periodic_mode: episodes
  periodic_value: 50
reward_weights:
  pnl: 1.0
  turn: 0.1
  dd: 0.2
  vol: 0.1
reward_tuner:
  enabled: true
  freq_episodes: 50
  delta: 0.05
  bounds:
    w_pnl:
    - 0.5
    - 3.0
    w_drawdown:
    - 0.0
    - 2.0
    w_volatility:
    - 0.0
    - 2.0
    w_turnover:
    - 0.0
    - 2.0
  score_weights:
    lambda_dd: 1.0
    kappa_consistency: 0.5
    mu_activity: 0.1
hybrid:
  enabled: true
  train_both: true
algo_controller:
  llm_enabled: false
stage_scheduler:
  enabled: true
paths:
  data_root: data
  raw_dir: data/raw
  logs_dir: logs
  reports_dir: reports
  checkpoints_dir: checkpoints
  models_dir: models
microstructure_v5:
  enabled: true
  orderbook_limit: 20
  window_seconds: 7200
  tick_interval_s: 1.0
  seed_from_klines: true
  seed_minutes: 120
  flush_every_n: 60
  out_dir: data/processed
